# services/crawler-orchestrator/src/main/resources/application-dev-local.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/app
    username: app
    password: app
  kafka:
    bootstrap-servers: localhost:19092
  redis:
    host: localhost
    port: 16379
  jpa:
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    dev.propprice.co: debug
  file:
    name: ./logs/app-dev-local.log

co:
  auth:
    enabled: false
  dispatcher:
    max-batch-size: 10
    tick-interval: 1000
